name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Specify the desired Node.js version
          target-architecture: 'node-17'

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          # Specify the desired JDK version
          distribution: 'adopt'
          java-version: '17'  # Adjust as needed

      - name: Build Docker image
        run: docker build -t your-image-name .

      - name: Push Docker image to Docker Hub (or your container registry)
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your-image-name
